/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkbenchTicketIdRouteImport } from './routes/workbench.$ticketId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkbenchTicketIdRoute = WorkbenchTicketIdRouteImport.update({
  id: '/workbench/$ticketId',
  path: '/workbench/$ticketId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/workbench/$ticketId': typeof WorkbenchTicketIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/workbench/$ticketId': typeof WorkbenchTicketIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/workbench/$ticketId': typeof WorkbenchTicketIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/workbench/$ticketId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/workbench/$ticketId'
  id: '__root__' | '/' | '/workbench/$ticketId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WorkbenchTicketIdRoute: typeof WorkbenchTicketIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workbench/$ticketId': {
      id: '/workbench/$ticketId'
      path: '/workbench/$ticketId'
      fullPath: '/workbench/$ticketId'
      preLoaderRoute: typeof WorkbenchTicketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WorkbenchTicketIdRoute: WorkbenchTicketIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
